import Head from 'next/head'
import ShowLayout from '../components/layouts/ShowLayout'
import VideoBox1 from '../components/VideoBox/VideoBox1/VideoBox1'
import SaleBox1 from '../components/SaleBox/SaleBox1/SaleBox1'

export default function AnimeBox() {
  return (<ShowLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>All Anime Box</h1>
      <div className="comp-space">
        <VideoBox1 />
      </div>
      <div className="comp-space">
        <SaleBox1 />
      </div>
    </ShowLayout>
  )
}
