import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";
import Banner1 from "../components/Banner/Banner1/Banner1";
import Banner2 from "../components/Banner/Banner2/Banner2";

export default function Banners() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Banners</h1>
      <div className="comp-space">
        <Banner1 />
      </div>
      <div className="comp-space">
        <Banner2 />
      </div>
    </MainLayout>
  );
}
