import Head from 'next/head'
import ShowLayout from '../components/layouts/ShowLayout'
import ProductHighlight1 from '../components/ProductHighlight/ProductHighlight1'

export default function ProductHighlights() {
  return (<ShowLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>All Product Highlights</h1>
      <div className="comp-space">
        <ProductHighlight1  />
      </div>
    </ShowLayout>
  )
}
